Repository alfa-laboratory/utils, pull requests merged in 2021-01, with the labels that each got.

#44 add format-phone utils
  packages/utils/src/format-phone/format/index.ts
  packages/utils/src/format-phone/format/util.test.ts
  packages/utils/src/format-phone/format/util.ts
  packages/utils/src/format-phone/get-raw/index.ts
  packages/utils/src/format-phone/get-raw/util.test.ts
  packages/utils/src/format-phone/get-raw/util.ts
  packages/utils/src/format-phone/index.ts
  packages/utils/src/index.ts
Labels: Новая фича, Ожидает ответа, Предложение по улучшению, требуется ревью

#45 fix(format-amount): fix typo
  packages/utils/src/format-amount/util.test.ts
  packages/utils/src/format-amount/util.ts
Labels: Мажорное изменение, Предложение по улучшению

#42 Turkish lira symbol change
  packages/data/src/currency/data.ts
Labels: Мажорное изменение, Предложение по улучшению, требуется ревью

#39 feat(data): add keyboard codes
  packages/data/src/index.ts
  packages/data/src/keyboard-codes/data.ts
  packages/data/src/keyboard-codes/index.ts
Labels: Новая фича, требуется ревью

#34 feat(hook): add useKeydownOutside
  packages/hooks/README.md
  packages/hooks/src/useKeydownOutside/hook.stories.tsx
  packages/hooks/src/useKeydownOutside/hook.ts
  packages/hooks/src/useKeydownOutside/index.ts
Labels: Новая фича, требуется ревью

#37 feat(hooks): add useDidUpdateEffect hook
  packages/hooks/README.md
  packages/hooks/src/useDidUpdateEffect/hook.stories.tsx
  packages/hooks/src/useDidUpdateEffect/hook.ts
  packages/hooks/src/useDidUpdateEffect/index.ts
Labels: Новая фича, Ожидает ответа, требуется ревью
